/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PortraitRouteImport } from './routes/portrait'
import { Route as GalerieRouteImport } from './routes/galerie'
import { Route as FonderieRouteImport } from './routes/fonderie'
import { Route as ExpositionsRouteImport } from './routes/expositions'
import { Route as EcranRouteImport } from './routes/ecran'
import { Route as CyanotypeRouteImport } from './routes/cyanotype'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as IndexRouteImport } from './routes/index'

const PortraitRoute = PortraitRouteImport.update({
  id: '/portrait',
  path: '/portrait',
  getParentRoute: () => rootRouteImport,
} as any)
const GalerieRoute = GalerieRouteImport.update({
  id: '/galerie',
  path: '/galerie',
  getParentRoute: () => rootRouteImport,
} as any)
const FonderieRoute = FonderieRouteImport.update({
  id: '/fonderie',
  path: '/fonderie',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpositionsRoute = ExpositionsRouteImport.update({
  id: '/expositions',
  path: '/expositions',
  getParentRoute: () => rootRouteImport,
} as any)
const EcranRoute = EcranRouteImport.update({
  id: '/ecran',
  path: '/ecran',
  getParentRoute: () => rootRouteImport,
} as any)
const CyanotypeRoute = CyanotypeRouteImport.update({
  id: '/cyanotype',
  path: '/cyanotype',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/cyanotype': typeof CyanotypeRoute
  '/ecran': typeof EcranRoute
  '/expositions': typeof ExpositionsRoute
  '/fonderie': typeof FonderieRoute
  '/galerie': typeof GalerieRoute
  '/portrait': typeof PortraitRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/cyanotype': typeof CyanotypeRoute
  '/ecran': typeof EcranRoute
  '/expositions': typeof ExpositionsRoute
  '/fonderie': typeof FonderieRoute
  '/galerie': typeof GalerieRoute
  '/portrait': typeof PortraitRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/cyanotype': typeof CyanotypeRoute
  '/ecran': typeof EcranRoute
  '/expositions': typeof ExpositionsRoute
  '/fonderie': typeof FonderieRoute
  '/galerie': typeof GalerieRoute
  '/portrait': typeof PortraitRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/cyanotype'
    | '/ecran'
    | '/expositions'
    | '/fonderie'
    | '/galerie'
    | '/portrait'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/cyanotype'
    | '/ecran'
    | '/expositions'
    | '/fonderie'
    | '/galerie'
    | '/portrait'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/cyanotype'
    | '/ecran'
    | '/expositions'
    | '/fonderie'
    | '/galerie'
    | '/portrait'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  CyanotypeRoute: typeof CyanotypeRoute
  EcranRoute: typeof EcranRoute
  ExpositionsRoute: typeof ExpositionsRoute
  FonderieRoute: typeof FonderieRoute
  GalerieRoute: typeof GalerieRoute
  PortraitRoute: typeof PortraitRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/portrait': {
      id: '/portrait'
      path: '/portrait'
      fullPath: '/portrait'
      preLoaderRoute: typeof PortraitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galerie': {
      id: '/galerie'
      path: '/galerie'
      fullPath: '/galerie'
      preLoaderRoute: typeof GalerieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fonderie': {
      id: '/fonderie'
      path: '/fonderie'
      fullPath: '/fonderie'
      preLoaderRoute: typeof FonderieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expositions': {
      id: '/expositions'
      path: '/expositions'
      fullPath: '/expositions'
      preLoaderRoute: typeof ExpositionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ecran': {
      id: '/ecran'
      path: '/ecran'
      fullPath: '/ecran'
      preLoaderRoute: typeof EcranRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cyanotype': {
      id: '/cyanotype'
      path: '/cyanotype'
      fullPath: '/cyanotype'
      preLoaderRoute: typeof CyanotypeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  CyanotypeRoute: CyanotypeRoute,
  EcranRoute: EcranRoute,
  ExpositionsRoute: ExpositionsRoute,
  FonderieRoute: FonderieRoute,
  GalerieRoute: GalerieRoute,
  PortraitRoute: PortraitRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
